#!/usr/bin/env zsh

set -euo pipefail

usage() {
    echo "Usage: source $0"
    echo "This script creates a temporary .env file, opens it in your default editor for you to add one or more"
    echo "secrets, and then sets those secrets as environment variables in your current shell session."
}

# Make sure that this file was "sourced" or else the envar won't stick
if [[ "$ZSH_EVAL_CONTEXT" != *":file"* ]]; then
    echo "Error: This script must be sourced."
    echo
    usage()
    exit 1
fi

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    usage()
    return 0
fi

temp_file=$(mktemp)
echo "MY_SECRET=your_secret_value" > "$temp_file"
trap 'rm -f "$temp_file"' EXIT

${EDITOR:-nano} "$temp_file"

if ! grep -qE '^[A-Za-z_][A-Za-z0-9_]*=.*$' "$temp_file"; then
  echo "Error: The file does not match the expected .env format."
  exit 1
fi

set -a
source $temp_file
set +a

echo "Done!"
