#!/usr/bin/env bash

set +e

if [[ $# != 1 || $1 == "--help" ]]; then
    echo "Usage: git-branchout <branch-name>"
    exit 0
fi

git auto-stash-if-necessary > /dev/null

git pull

echo "Creating branch $1..."
git branch $1
git checkout $1

git-auto-unstash-if-necessary > /dev/null
