#!/usr/bin/env bash

set +e

if [[ $# != 1 || $1 == "--help" ]]; then
    echo "Usage: git-branchout <branch-name>"
    exit 0
fi

STASH="false"
if ! git-is-clean; then
    STASH="true"
    git stash save -u "Automatic stash by $0"
fi

echo "Creating branch $1..."
git branch $1
git checkout $1

if [[ $STASH = "true" ]]; then
    echo "Popping stash..."
    git stash pop
fi
