#!/bin/bash

if [[ $# != 1 || $1 == "--help" ]]; then
    echo "Usage: $0 [<stash message>]"
    echo "This script effectively runs \`git stash\` on staged changes"
    exit 0
fi

# It's been a while; I think this is correct?
git stash push --keep-index && git stash -u $1 && git stash pop stash@{1}
