#!/usr/bin/env bash

set +e

# TODO add param validation

STASH="false"
if ! git-is-clean; then
    STASH="true"
    git stash save -u "Automatic stash by $0"
fi

git branch $1
git checkout $1

if [[ $STASH = "true" ]]; then
    echo "Popping stash..."
    git stash pop
fi
