#!/bin/bash

# Author: Adam Hintz <adamh.zero@gmail.com>

if [[ $# != 2 ]]; then
    echo "Usage: mvln <current> <new>"
    exit 1
fi

CURRENT=$1
NEW=$2

mkdir -p `dirname $NEW`
mv $CURRENT $NEW
ln -s $NEW $CURRENT
