#!/bin/bash

if [[ $# != 2 ]]; then
    echo "Usage: mvln <current> <new>"
    # TODO can fix where I don't need this second line?
    echo "(where <new> contains the basename of <current>)"
    exit 1
fi

CURRENT=$1
NEW=$2

mkdir -p `dirname $NEW`
mv $CURRENT $NEW
# TODO in order to replace if something already exists, -sif ?
ln -s $NEW $CURRENT
