#!/bin/bash

if [[ $# -gt 3 || $# -lt 2 ]]; then
    echo "Usage: mvln [-f] <current> <new>"
    echo "Example: mvln .bashrc ~/src/dotfiles/.bashrc"
    exit 0
fi

FORCE=
if [[ "$1" == "-f" ]]; then
    FORCE=true
    shift
fi

CURRENT="$1"
NEW="$2"

[[ -e "$(dirname $NEW)" ]] || mkdir -p "$(dirname $NEW)"

if [[ -e "$NEW" ]]; then
    if [[ -d "$NEW" ]]; then
        echo "'$NEW' is an existing directory; refusing to remove it"
        exit 1
    fi

    if [[ -L "$CURRENT" ]]; then
        echo "'$CURRENT' is already a symlink"
        exit 1
    fi

    if [[ "$FORCE" != true ]]; then
        if ! diff -q "$CURRENT" "$NEW" > /dev/null; then
            echo "File '$NEW' already exists and is not the same as '$CURRENT'"
            exit 1
        fi
    fi
fi

mv $CURRENT $NEW
ln -s $NEW $CURRENT
