#!/bin/bash -i

# Author: Adam Hintz <adamh.zero@gmail.com>

# Repeat a command every $1 seconds

time="$1"
shift 1

while : ; do
    eval $@

    sleep "$time"
    if [[ $? != 0 ]]; then
        exit $?
    fi
done
